version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
      # debug port
      - "40000:40000"
    environment:
      - POSTGRES_DSN=postgresql://guest:guest@postgres:5432/quest-app-db?sslmode=disable # Test credentials
      - ENVIRONMENT=${ENVIRONMENT:-docker}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:-secret-key}
    # debug options
    env_file:
      - ./.env
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec ./server
    depends_on:
      - postgres
    volumes:
      - ./files:/root/files:consistent
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: quest-app-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: