version: "3.9"
services:
  app:
    image: superhorsy/quest
    build: .
    ports:
      - ${APP_PORT:-8080}:8080
    env_file:
      - ./.env
    volumes:
      - ./files:/root/files:consistent
      - $HOME/.postgresql/:/root/.postgresql  # pass postgres sql (or cockroach sql) root cert
