version: "3.9"
services:
  app:
    image: superhorsy/quest
    build: .
    ports:
      - ${APP_PORT:-8080}:8080
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./files:/root/files:consistent
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: quest-app-db
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: