version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
      # debug port
      - "40000:40000"
    env_file:
      - ./.env
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec ./server
    volumes:
      - ./files:/root/files:consistent